### ISSUE TITLE
Folien für Module 2 Digitaler Arbeitsplatz vorbereiten

### ISSUE THREAD

**Issue by larnsce** [rstatszh-k009/website#1]
Lieber Philipp, ich habe das Grundgerüst für das zweite Modul vorbereitet. Dort habe ich einen Platzhalter für eure Inhalte. Möchtet ihr eigene Folien verwenden oder diese hier integrieren? 

Für die Vorstellung bräuchte ich ein Profilfoto von dir und Thomas und dann drei Punkt die euch beschreiben:

https://github.com/rstatszh-k009/website/blob/52dadf0d3b39a19cff5e4cd2a3ca532b518c26d9/folien/md-02-datenvisualisierung.qmd#L196

Bei mir sieht das so aus:

https://github.com/rstatszh-k009/website/blob/52dadf0d3b39a19cff5e4cd2a3ca532b518c26d9/folien/md-01-willkommen.qmd#L32

**Comment by philbosch** [comment]
@larnsce magst du mich noch assignen für das Issue? Kann das leider selbst nicht.

**Comment by philbosch** [comment]
@larnsce kannst du Thomas (https://github.com/ThomasKnecht) und mir noch Bearbeitungsrechte für das Repo/die Orga geben? Dann können wir unsere Anpassungen selbst einpflegen via PR
Merci :)

**Comment by larnsce** [comment]
@philbosch, ich habe dich und @ThomasKnecht soeben zur Organisation eingeladen und "Owner" Rechte gegeben.

**Comment by larnsce** [comment]
Danke!
